#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright © 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Author: Tencent AI Arena Authors

Monitor panel configuration builder for Gorge Chase.
峡谷追猎监控面板配置构建器。
"""


from kaiwudrl.common.monitor.monitor_config_builder import MonitorConfigBuilder


def build_monitor():
    """
    # This function is used to create monitoring panel configurations for custom indicators.
    # 该函数用于创建自定义指标的监控面板配置。
    """
    monitor = MonitorConfigBuilder()

    config_dict = (
        monitor.title("峡谷追猎")
        .add_group(
            group_name="算法指标",
            group_name_en="algorithm",
        )
        .add_panel(
            name="累积回报",
            name_en="reward",
            type="line",
        )
        .add_metric(
            metrics_name="reward",
            expr="avg(reward{})",
        )
        .end_panel()
        .add_panel(
            name="存活奖励分量",
            name_en="reward_alive",
            type="line",
        )
        .add_metric(
            metrics_name="reward_alive",
            expr="avg(reward_alive{})",
        )
        .end_panel()
        .add_panel(
            name="宝箱奖励分量",
            name_en="reward_treasure",
            type="line",
        )
        .add_metric(
            metrics_name="reward_treasure",
            expr="avg(reward_treasure{})",
        )
        .end_panel()
        .add_panel(
            name="Buff奖励分量",
            name_en="reward_buff",
            type="line",
        )
        .add_metric(
            metrics_name="reward_buff",
            expr="avg(reward_buff{})",
        )
        .end_panel()
        .add_panel(
            name="靠近宝箱分量",
            name_en="reward_approach",
            type="line",
        )
        .add_metric(
            metrics_name="reward_approach",
            expr="avg(reward_approach{})",
        )
        .end_panel()
        .add_panel(
            name="脱离危险分量",
            name_en="reward_escape_danger",
            type="line",
        )
        .add_metric(
            metrics_name="reward_escape_danger",
            expr="avg(reward_escape_danger{})",
        )
        .end_panel()
        .add_panel(
            name="危险抢箱分量",
            name_en="reward_treasure_danger",
            type="line",
        )
        .add_metric(
            metrics_name="reward_treasure_danger",
            expr="avg(reward_treasure_danger{})",
        )
        .end_panel()
        .add_panel(
            name="无效移动分量",
            name_en="reward_invalid_move",
            type="line",
        )
        .add_metric(
            metrics_name="reward_invalid_move",
            expr="avg(reward_invalid_move{})",
        )
        .end_panel()
        .add_panel(
            name="闪现失败惩罚分量",
            name_en="reward_bad_flash",
            type="line",
        )
        .add_metric(
            metrics_name="reward_bad_flash",
            expr="avg(reward_bad_flash{})",
        )
        .end_panel()
        .add_panel(
            name="新开地图分量",
            name_en="reward_explore_map",
            type="line",
        )
        .add_metric(
            metrics_name="reward_explore_map",
            expr="avg(reward_explore_map{})",
        )
        .end_panel()
        .add_panel(
            name="重复经过分量",
            name_en="reward_repeat",
            type="line",
        )
        .add_metric(
            metrics_name="reward_repeat",
            expr="avg(reward_repeat{})",
        )
        .end_panel()
        .add_panel(
            name="拖延惩罚分量",
            name_en="reward_procrastination",
            type="line",
        )
        .add_metric(
            metrics_name="reward_procrastination",
            expr="avg(reward_procrastination{})",
        )
        .end_panel()
        .add_panel(
            name="终局奖励分量",
            name_en="reward_terminal",
            type="line",
        )
        .add_metric(
            metrics_name="reward_terminal",
            expr="avg(reward_terminal{})",
        )
        .end_panel()
        .add_panel(
            name="撞墙次数",
            name_en="n_hit_wall",
            type="line",
        )
        .add_metric(
            metrics_name="n_hit_wall",
            expr="avg(n_hit_wall{})",
        )
        .end_panel()
        .add_panel(
            name="地图采样次数",
            name_en="map_sample_count",
            type="line",
        )
        .add_metric(
            metrics_name="map_sample_count_1",
            expr="avg(map_sample_count_1{})",
        )
        .add_metric(
            metrics_name="map_sample_count_2",
            expr="avg(map_sample_count_2{})",
        )
        .add_metric(
            metrics_name="map_sample_count_3",
            expr="avg(map_sample_count_3{})",
        )
        .add_metric(
            metrics_name="map_sample_count_4",
            expr="avg(map_sample_count_4{})",
        )
        .add_metric(
            metrics_name="map_sample_count_5",
            expr="avg(map_sample_count_5{})",
        )
        .add_metric(
            metrics_name="map_sample_count_6",
            expr="avg(map_sample_count_6{})",
        )
        .add_metric(
            metrics_name="map_sample_count_7",
            expr="avg(map_sample_count_7{})",
        )
        .add_metric(
            metrics_name="map_sample_count_8",
            expr="avg(map_sample_count_8{})",
        )
        .add_metric(
            metrics_name="map_sample_count_9",
            expr="avg(map_sample_count_9{})",
        )
        .add_metric(
            metrics_name="map_sample_count_10",
            expr="avg(map_sample_count_10{})",
        )
        .end_panel()
        .add_panel(
            name="总损失",
            name_en="total_loss",
            type="line",
        )
        .add_metric(
            metrics_name="total_loss",
            expr="avg(total_loss{})",
        )
        .end_panel()
        .add_panel(
            name="价值损失",
            name_en="value_loss",
            type="line",
        )
        .add_metric(
            metrics_name="value_loss",
            expr="avg(value_loss{})",
        )
        .end_panel()
        .add_panel(
            name="策略损失",
            name_en="policy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="policy_loss",
            expr="avg(policy_loss{})",
        )
        .end_panel()
        .add_panel(
            name="熵损失",
            name_en="entropy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="entropy_loss",
            expr="avg(entropy_loss{})",
        )
        .end_panel()
        .add_panel(
            name="学习率",
            name_en="lr",
            type="line",
        )
        .add_metric(
            metrics_name="lr",
            expr="avg(lr{})",
        )
        .end_panel()
        .add_panel(
            name="熵系数",
            name_en="ent_coef",
            type="line",
        )
        .add_metric(
            metrics_name="ent_coef",
            expr="avg(ent_coef{})",
        )
        .end_panel()
        .end_group()
        .build()
    )
    return config_dict
